# Generated by Django 2.1.5 on 2019-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20190729_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
