# Generated by Django 2.1.5 on 2019-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
