# Generated by Django 2.1.5 on 2019-08-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20190731_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products1/%Y/%m/%d'),
        ),
    ]
