# Generated by Django 2.1.5 on 2019-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_auto_20190806_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
