# Generated by Django 2.1.5 on 2019-08-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_auto_20190827_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_r',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='them_products', to='package.Price_list'),
            preserve_default=False,
        ),
    ]
