# Generated by Django 2.1.5 on 2019-08-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_product_price_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fest_f',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='offer_products', to='package.fest_offer'),
            preserve_default=False,
        ),
    ]
