# Generated by Django 2.1.5 on 2019-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_product_fest_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Destinations',
            field=models.CharField(choices=[('International Destinations', 'INTERNATIONAL'), ('Destinations within India', 'INDIA')], default='INTERNATIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Destinations',
            field=models.CharField(choices=[('International Destinations', 'INTERNATIONAL'), ('Destinations within India', 'INDIA')], default='INTERNATIONAL', max_length=50),
        ),
    ]
